# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8495c3f33aca80f5117a4eda0245be3723d3e420bc7ad697ac91bd3409a4caabb6a350a89033d96894faed73cf3f0b9534c7179d871284e16b9b7f7abe17fb6a

test:
  secret_key_base: 9e8f98754ef8714b9e0f81b98444633548a800d6fe50b0ce8847bc1d072355dab605393038aa6cc8e3dfbcfd37f2cbbb53a261add15afea077663544f34adbbb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
